# Generated by Django 5.2.7 on 2025-10-24 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tech', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='author',
        ),
        migrations.RemoveField(
            model_name='userquizattempt',
            name='quiz',
        ),
        migrations.RemoveField(
            model_name='userquizattempt',
            name='user',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='Quiz',
        ),
        migrations.DeleteModel(
            name='UserQuizAttempt',
        ),
    ]
